---
- hosts: em-ansible-host
  tasks:
  - name: change vm config
    uri:
      url: https://em13-test.gdn.aus.osc:7803/em/cloud/iaas/server/vm/F2002C3D2B27DFF4EBD522BCA46A3571?resource_state
      method: PUT
      return_content: yes
      headers: 
        Content-Type: application/oracle.com.cloud.common.VM+json
      user: osc_anz_admin
      password: welcome1
      validate_certs: no
      force_basic_auth: yes
      body: {"cpu":[1,0],"memory":"2048"}
      body_format: json 
    register: output_vmconfig
  - name: output vmconfig
    #all works fine
    #debug: var=output_vmconfig
    #debug: var=output_vmconfig.status
    debug: var=output_vmconfig.msg
    #debug: msg="{{ output_vmconfig }}"
