- hosts: all
  remote_user: root

  # here we make a variable named "proxy_env" that is a dictionary
  vars:
    proxy_env:
      http_proxy: http://www-proxy.osc.au.oracle.com:80

  tasks:

    - yum: name=cobbler state=installed
      environment: "{{proxy_env}}"
