---
- hosts: em-ansible-host
  tasks:
  - name: show vm status
    uri:
      url: https://em13-test.gdn.aus.osc:7803/em/cloud/iaas/server/byrequest/161?status,uri
      method: GET
      return_content: yes
      user: osc_anz_admin
      password: welcome1
      validate_certs: no
      force_basic_auth: yes
      body_format: json 
    register: showvmstatus
  - name: show list
    #debug: var=showvmstatus
    debug: var=showvmstatus.content
    #debug: msg="{{ showvmstatus | to_nice_json(indent=5) }}"
